<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: PUT, GET, POST");
header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
include_once "../connexion_base.php";
$data = json_decode( file_get_contents('php://input'),true );
$id= $data['id'];
$nom =  $data['nom'];
$prenom =  $data['prenom'];
$ce =  $data['ce'];
$cni =  $data['cni'];
$tel =  $data['tel'];
$comite_id =  $data['comite_id'];
$departement =  $data['departement'];
$region =  $data['region'];
$collectivite =  $data['collectivite'];
$dateN =  $data['dateNaissance'];
$pays =  $data['pays'];
$sexe =  $data['sexe'];
$lvote =  $data['lvote'];
$bvote =  $data['bvote'];
$con=new connexion_base();
$con->connexionBDD();
$con->set['nom']=$nom;
$con->set['prenom']=$prenom;
$con->set['ce']=$ce;
$con->set['cni']=$cni;
$con->set['phone']=$tel;
$con->set['comite_id']=$comite_id;
$con->set['departement']=$departement;
$con->set['region']=$region;
$con->set['collectivite']=$collectivite;
$con->set['dateNaissance']=$dateN;
$con->set['sexe']=$sexe;
$con->set['lvote']=$lvote;
$con->set['bvote']=$bvote;
$con->set['pays']=$pays;
$con->where['ind']=$id;
$con->MyExecuteUpdate('parrains');
$con=null;