<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: PUT, GET, POST");
header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
include_once "../connexion_base.php";
$data = json_decode( file_get_contents('php://input'),true );
$id= $data['id'];
$nom =  $data['nom'];
$prenom =  $data['prenom'];
$email =  $data['email'];
$tel1 =  $data['tel1'];
$tel2 =  $data['tel2'];
$con=new connexion_base();
$con->connexionBDD();
$con->set['nom']=$nom;
$con->set['prenom']=$prenom;
$con->set['email']=$email;
$con->set['tel2']=$tel2;
$con->set['tel1']=$tel1;
$con->where['ind']=$id;
$con->MyExecuteUpdate('responsable');
$con=null;